name: Linux Packaging

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deb:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install FPM
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev build-essential
          sudo gem install --no-document fpm

      - name: Install Python deps & PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build standalone binary
        run: |
          pyinstaller --onefile --name WordWings wordwings_app.py

      - name: Package .deb
        run: |
          mkdir -p pkg/opt/wordwings
          cp dist/WordWings pkg/opt/wordwings/WordWings
          fpm -s dir -t deb \
            -n wordwings \
            -v 1.0.0 \
            --prefix /opt/wordwings \
            --description "WordWings Reading Support Tool" \
            --license MIT \
            pkg/opt/wordwings

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v3
        with:
          name: WordWings-deb
          path: wordwings_1.0.0_amd64.deb
