name: Build & Release Windows Installer

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-installer:
    runs-on: windows-latest

    steps:
      # 1. Check out your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Install pip + project dependencies
      - name: Install Python dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      # 4. Build the standalone EXE
      - name: Build standalone EXE
        shell: pwsh
        run: |
          pyinstaller --onefile --windowed --add-data 'config.ini;.' --name WordWings wordwings.py

      # 5. Install Inno Setup via Chocolatey
      - name: Install Inno Setup
        shell: pwsh
        run: choco install innosetup -y

      # 6. Generate the Inno Setup script (installer.iss) via a PowerShell here‐string
      - name: Generate Inno Setup script
        shell: pwsh
        run: |
          $script = @'
[Setup]
AppName=WordWings
AppVersion=${{ github.ref_name }}
DefaultDirName={pf}\WordWings
DefaultGroupName=WordWings
OutputDir=.
OutputBaseFilename=WordWingsSetup
Compression=lzma
SolidCompression=yes

[Files]
Source: "dist\WordWings.exe"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\WordWings"; Filename: "{app}\WordWings.exe"
Name: "{commondesktop}\WordWings"; Filename: "{app}\WordWings.exe"

[Run]
Filename: "{app}\WordWings.exe"; Description: "Launch WordWings"; Flags: nowait postinstall skipifsilent
'@
          # Write out the ISS file with ASCII encoding:
          $script | Set-Content installer.iss -Encoding ASCII

      # 7. Compile the NSIS installer
      - name: Compile Windows installer
        shell: pwsh
        run: |
          & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' installer.iss

      # 8. Publish a GitHub Release with your assets
      - name: Publish Release & Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: WordWings ${{ github.ref_name }}
          files: |
            dist/WordWings.exe
            WordWingsSetup.exe
            WordWings-final.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
